## 넘파이?

Numerical Python - 행열 연산이나 다차원 배열을 편리하게 처리  
배열(array) 단위로 백터, 행열 연상등을 파이썬의 기본 리스트에 비해 빠르고 적은양의 메모리로 연산  
브로드캐스트 지원 - 형태(차원)가 다른 행렬끼리의 계산

https://numpy.org/

In [69]:
import numpy as np

## 사용하는 이유?

In [2]:
matrix_1 = [[1, 2],[3, 4]]
matrix_2 = [[5, 6],[7, 8]]

matrix_result = []

#행렬합 (파이썬 리스트사용)
for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j]+matrix_2[i][j])
    matrix_result.append(tmp)
    
print(matrix_result)

[[6, 8], [10, 12]]


In [4]:
matrix_1 = [[1, 2],[3, 4]]
matrix_2 = [[5, 6],[7, 8]]

In [8]:
print(np.array(matrix_1))
print(type(np.array(matrix_1)))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [5]:
#행렬합 (넘파이)
matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[ 6  8]
 [10 12]]


In [3]:
#숫자와의 연산 (파이썬 리스트사용)

matrix_1 = [[1, 2],[3, 4]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_2)):
        matrix_1[i][j] = matrix_1[i][j] + 1
        
print(matrix_1)

[[2, 3], [4, 5]]


In [9]:
#숫자와의 연산 (넘파이)

matrix_1 = [[1, 2],[3, 4]]

print(np.array(matrix_1) + 1)

[[2 3]
 [4 5]]


In [13]:
matrix_1 = [['aa', 'bb'],[3.4, 1]]

np.array(matrix_1)

array([['aa', 'bb'],
       ['3.4', '1']], dtype='<U32')

## 속도비교

In [14]:
import time

size = 10000000

#list
x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린시간", time.time()-start_time)

리스트 걸린시간 2.0846636295318604


In [15]:
#adlist (넘파이)
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간", time.time()-start_time)

넘파이 걸린시간 0.049451589584350586


## ndarray

In [17]:
x = np.uint(32)
print(x)
print(type(x))
print(x.dtype)

32
<class 'numpy.uint64'>
uint64


In [19]:
x = np.array([1, 2, 3, 4])
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [20]:
x = np.float32([1, 2, 3, 4])
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [21]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [22]:
x = np.int32(x)
print(x)
print(x.dtype)

[1 2 3 4]
int32


In [23]:
np.issubdtype(x.dtype, np.int32)

True

## 다차원 ndarray

In [24]:
x = np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)

()
0
1


In [27]:
x = np.array([1, 2])
print(x.shape)
print(x.ndim)
print(x.size)

(2,)
1
2


In [32]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 3)
2
6


In [33]:
x = np.array([[[1, 2, 3],[4, 5, 6]], [[7,8,9], [10,11,12]]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 2, 3)
3
12


## arange

In [34]:
x = np.arange(10)
print(x)
x = np.arange(10.0)
print(x)
x = np.arange(1, 10, 2)
print(x)
x = np.arange(1, 10, 0.5)
print(x)
x = np.arange(10, 1, -0.5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


## linspace

In [35]:
x = np.linspace(1, 20, 5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [38]:
x = np.linspace(1, 20, 10, endpoint=False)
print(x)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


## reshape

In [40]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [41]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
x = np.arange(24).reshape(2, 3, 4)
print(x.ndim)
print(x.size)
print(x.shape)

3
24
(2, 3, 4)


In [48]:
x = np.arange(16).reshape(2, 2, 2, 2)
print(x)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [50]:
x = np.array([[1,2],[3,4],[5,6]])
# print(x)
# print(x.shape)
print(x.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [54]:
x = np.arange(9).reshape(3, -1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## slicing

In [55]:
x = np.arange(20)
print(x[1:3])

[1 2]


In [58]:
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [59]:
x = np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


## indexing & boolean indexing

In [62]:
a = np.arange(20).reshape(4, 5)
print(a)

# print(a[1][1])
# print(a[1,1])
# print(a[[1,1],[1,2]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[6 7]


In [68]:
a = np.arange(20).reshape(4, 5)
print(a)

# print(a > 3)
# print(a[a > 3])
# print(a[a == 1])
# print(a[~(a == 1)])
print(a[(a > 3)&(a < 8)])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[4 5 6 7]


## random

In [74]:
np.random.rand(5, 5)

array([[0.85059578, 0.87610653, 0.67663911, 0.95251333, 0.85866775],
       [0.6014378 , 0.61917927, 0.20336577, 0.65516542, 0.59221641],
       [0.58192156, 0.21599626, 0.63431757, 0.10746769, 0.9152866 ],
       [0.61737544, 0.68192072, 0.36929106, 0.79977644, 0.06408918],
       [0.39753181, 0.73421918, 0.28790632, 0.79098905, 0.32766844]])

In [80]:
np.random.randint(1, 10)

8

In [81]:
np.random.randint(1, 10, size=(5))

array([1, 8, 4, 5, 8])

In [85]:
x = np.random.randint(1, 10, size=(5, 5))
print(x)

[[1 5 1 3 3]
 [4 4 1 2 4]
 [2 7 6 7 3]
 [2 4 2 7 5]
 [9 5 6 6 8]]


In [90]:
x.ravel(order='C')

array([1, 5, 1, 3, 3, 4, 4, 1, 2, 4, 2, 7, 6, 7, 3, 2, 4, 2, 7, 5, 9, 5,
       6, 6, 8])

## 특별한 형태의 배열

In [91]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
x = np.random.randint(1, 10, size=(5, 5))
y = np.eye(5)
print(x)
z = np.dot(x, y)
print(z)

[[2 3 9 2 5]
 [9 5 1 9 2]
 [5 4 4 9 9]
 [8 9 2 3 1]
 [1 4 7 9 3]]
[[2. 3. 9. 2. 5.]
 [9. 5. 1. 9. 2.]
 [5. 4. 4. 9. 9.]
 [8. 9. 2. 3. 1.]
 [1. 4. 7. 9. 3.]]


In [97]:
x = np.random.randint(1, 10, size=(5, 5))
print(x)
print(x.ravel())
print(x.ravel(order='F'))

[[9 5 3 1 7]
 [2 4 2 5 5]
 [7 3 5 3 1]
 [9 3 6 2 9]
 [2 3 6 8 2]]
[9 5 3 1 7 2 4 2 5 5 7 3 5 3 1 9 3 6 2 9 2 3 6 8 2]
[9 2 7 9 2 5 4 3 3 3 3 2 5 6 6 1 5 3 2 8 7 5 1 9 2]


## concatenate

In [98]:
x = np.arange(1, 4)
y = np.arange(4, 7)
print(x)
print(y)
np.concatenate([x, y])

[1 2 3]
[4 5 6]


array([1, 2, 3, 4, 5, 6])

In [99]:
x + y

array([5, 7, 9])

In [100]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
print(x)
print(y)
np.concatenate([x, y])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

## split

In [105]:
x = np.arange(12)
print(x)
np.split(x, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [106]:
x = np.arange(16).reshape(4, 4)
print(x)
np.split(x, 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [107]:
x = np.arange(16).reshape(4, 4)
print(x)
np.split(x, 2, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## broadcast

In [108]:
x = np.array([1,2,3])
x + 1

array([2, 3, 4])

In [109]:
x = np.arange(1, 10).reshape(3, 3)
print(x)
y = np.arange(1, 4)
print(y)
x + y

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [110]:
x = np.array([10, 20, 30]).reshape(3, 1)
print(x)
y = np.arange(1, 4)
print(y)
x + y

[[10]
 [20]
 [30]]
[1 2 3]


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## 연산 및 집계함수

In [112]:
x = np.arange(3, 7).reshape(2, 2)
print(x)
y = np.arange(4).reshape(2, 2)
print(y)
x.dot(y) #행렬곱

[[3 4]
 [5 6]]
[[0 1]
 [2 3]]


array([[ 8, 15],
       [12, 23]])

In [113]:
np.transpose(x) #전치행렬

array([[3, 5],
       [4, 6]])

In [114]:
np.linalg.inv(x) #역행렬

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [115]:
np.linalg.det(x) #행렬식

-1.9999999999999971

In [116]:
np.median(x) #중간값

4.5

In [117]:
np.std(x) #표준편차

1.118033988749895

In [118]:
np.var(x) #분산

1.25

In [119]:
np.sum(x) #합

18

In [121]:
print(x)

[[3 4]
 [5 6]]


In [123]:
np.sum(x, axis=1) #합, 축변경

array([ 7, 11])

In [124]:
np.cumsum(x) #누적합

array([ 3,  7, 12, 18])

In [125]:
np.argmin(x) #최소값 위치

0

In [126]:
np.argmax(x) #최대값 위치

3

In [127]:
x[0][0] = 0

In [128]:
x

array([[0, 4],
       [5, 6]])

In [129]:
np.any(x) #하나라도 참이어야 참

True

In [131]:
x[0][0] = 3

In [134]:
print(x)

[[3 4]
 [5 6]]


In [132]:
np.all(x) #모든요소가 참이어야 참

True

In [140]:
print((x > 4).dtype)

bool


In [133]:
np.all(x > 4)

False

In [142]:
print(x)

[[3 4]
 [5 6]]


In [141]:
np.where(x > 4)

(array([1, 1]), array([0, 1]))

In [143]:
np.where(x > 4, x, -100)

array([[-100, -100],
       [   5,    6]])

## 실습1

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [10, 20, 30, 40, 50, 60, 70, 80, 90]

x = np.array(x).reshape(3, 3)
y = np.array(y).reshape(3, 3)

print(x + y)
print(x.dot(y))

## 실습2

In [ ]:
x = np.linspace(1, 20, 30)
x = x + 10
print(x)

## 실습3

In [ ]:
x = np.random.randint(1, 100, size=(200)).reshape(2, 10, 10)
print(x)
x = np.where(x>=50, 1, 2)
print(x)
print(x[1][5:,5:])